In [5]:
import pandas as pd

In [ ]:
import fastf1
fastf1.Cache.enable_cache('../data/raw')
session = fastf1.get_session(2025, 21, 'Qualifying')
session.load()
laps = session.laps

In [7]:
laps

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,...,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate
0,0 days 00:22:35.900000,NOR,4,NaT,1.0,1.0,0 days 00:20:56.651000,NaT,NaT,0 days 00:00:47.899000,...,True,McLaren,0 days 00:20:56.651000,2025-11-08 18:06:48.087,1,NaN,False,,False,False
1,0 days 00:23:46.304000,NOR,4,0 days 00:01:10.404000,2.0,1.0,NaT,NaT,0 days 00:00:18.229000,0 days 00:00:36.070000,...,True,McLaren,0 days 00:22:35.900000,2025-11-08 18:08:27.336,1,NaN,False,,False,True
2,0 days 00:25:39.298000,NOR,4,0 days 00:01:52.994000,3.0,1.0,NaT,NaT,0 days 00:00:45.794000,0 days 00:00:45.129000,...,True,McLaren,0 days 00:23:46.304000,2025-11-08 18:09:37.740,1,NaN,False,,False,True
3,0 days 00:27:34.678000,NOR,4,0 days 00:01:55.380000,4.0,1.0,NaT,NaT,0 days 00:00:42.694000,0 days 00:00:55.002000,...,True,McLaren,0 days 00:25:39.298000,2025-11-08 18:11:30.734,1,NaN,False,,False,True
4,0 days 00:28:44.927000,NOR,4,0 days 00:01:10.249000,5.0,1.0,NaT,NaT,0 days 00:00:18.149000,0 days 00:00:36.079000,...,True,McLaren,0 days 00:27:34.678000,2025-11-08 18:13:26.114,1,NaN,False,,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
311,0 days 00:28:13.107000,TSU,22,0 days 00:01:11.012000,5.0,1.0,NaT,NaT,0 days 00:00:18.315000,0 days 00:00:36.546000,...,True,Red Bull Racing,0 days 00:27:02.095000,2025-11-08 18:12:53.531,1,NaN,False,,False,True
312,0 days 00:29:41.033000,TSU,22,0 days 00:01:27.926000,6.0,1.0,NaT,0 days 00:29:38.096000,0 days 00:00:21.243000,0 days 00:00:41.287000,...,True,Red Bull Racing,0 days 00:28:13.107000,2025-11-08 18:14:04.543,1,NaN,False,,False,False
313,0 days 00:35:19.135000,TSU,22,NaT,7.0,2.0,0 days 00:33:19.412000,NaT,NaT,0 days 00:00:47.324000,...,True,Red Bull Racing,0 days 00:29:41.033000,2025-11-08 18:15:32.469,1,NaN,False,,False,False
314,0 days 00:36:29.846000,TSU,22,0 days 00:01:10.711000,8.0,2.0,NaT,NaT,0 days 00:00:18.335000,0 days 00:00:36.256000,...,True,Red Bull Racing,0 days 00:35:19.135000,2025-11-08 18:21:10.571,1,NaN,False,,False,True
315,0 days 00:38:10.007000,TSU,22,0 days 00:01:40.161000,9.0,2.0,NaT,0 days 00:38:07.127000,0 days 00:00:25.947000,0 days 00:00:44.650000,...,True,Red Bull Racing,0 days 00:36:29.846000,2025-11-08 18:22:21.282,1,NaN,False,,False,False

In [8]:
faster_laps = laps.groupby(by=['Driver'], as_index=False)[['LapTime']].min().sort_values(by=['LapTime'])

In [9]:
sectors = laps[['Driver', 'Sector1Time', 'Sector2Time', 'Sector3Time']]

faster_sectors = (sectors.groupby(by=['Driver'], as_index=False).min())

In [10]:
bestS1 = faster_sectors['Sector1Time'].min()
bestS2 = faster_sectors['Sector2Time'].min()
bestS3 = faster_sectors['Sector3Time'].min()

In [11]:
ideal_lap = bestS1 + bestS2 + bestS3

In [12]:
def fix_time(x:str):
    return x[6:]

In [13]:
faster_laps.merge(right=faster_sectors,
                  how='left',
                  on='Driver',
                 )

,Driver,LapTime,Sector1Time,Sector2Time,Sector3Time
0,NOR,0 days 00:01:09.511000,0 days 00:00:17.998000,0 days 00:00:35.534000,0 days 00:00:15.941000
1,ANT,0 days 00:01:09.685000,0 days 00:00:18.035000,0 days 00:00:35.582000,0 days 00:00:16.038000
2,BEA,0 days 00:01:09.755000,0 days 00:00:18.062000,0 days 00:00:35.641000,0 days 00:00:15.994000
3,LEC,0 days 00:01:09.801000,0 days 00:00:18.012000,0 days 00:00:35.680000,0 days 00:00:16.034000
4,PIA,0 days 00:01:09.835000,0 days 00:00:18.127000,0 days 00:00:35.596000,0 days 00:00:16.030000
5,GAS,0 days 00:01:09.857000,0 days 00:00:18.075000,0 days 00:00:35.643000,0 days 00:00:15.974000
6,RUS,0 days 00:01:09.880000,0 days 00:00:18.081000,0 days 00:00:35.748000,0 days 00:00:16.033000
7,HAD,0 days 00:01:09.931000,0 days 00:00:18.086000,0 days 00:00:35.690000,0 days 00:00:15.981000
8,LAW,0 days 00:01:09.950000,0 days 00:00:18.164000,0 days 00:00:35.677000,0 days 00:00:15.984000
9,HUL,0 days 00:01:09.985000,0 days 00:00:18.183000,0 days 00:00:35.680000,0 days 00:00:15.954000
10,ALO,0 days 00:01:10.001000,0 days 00:00:18.138000,0 days 00:00:35.722000,0 days 00:00:16.016000
11,HAM,0 days 00:01:10.016000,0 days 00:00:18.121000,0 days 00:00:35.714000,0 days 00:00:16.071000
12,STR,0 days 00:01:10.041000,0 days 00:00:18.137000,0 days 00:00:35.791000,0 days 00:00:16.113000
13,ALB,0 days 00:01:10.053000,0 days 00:00:18.006000,0 days 00:00:35.891000,0 days 00:00:16.090000
14,SAI,0 days 00:01:10.184000,0 days 00:00:18.146000,0 days 00:00:35.866000,0 days 00:00:16.086000
15,VER,0 days 00:01:10.403000,0 days 00:00:18.178000,0 days 00:00:36.036000,0 days 00:00:16.099000
16,OCO,0 days 00:01:10.438000,0 days 00:00:18.382000,0 days 00:00:35.915000,0 days 00:00:16.141000
17,COL,0 days 00:01:10.632000,0 days 00:00:18.163000,0 days 00:00:36.261000,0 days 00:00:16.147000
18,TSU,0 days 00:01:10.711000,0 days 00:00:18.315000,0 days 00:00:36.256000,0 days 00:00:16.120000

In [14]:
faster_laps['IdealLap'] = ideal_lap

faster_laps['DiffLap'] = faster_laps['LapTime'] - faster_laps['IdealLap']

In [15]:
faster_laps['LapTimeSec'] = faster_laps['LapTime'].dt.total_seconds()
faster_laps['IdealLapSec'] = faster_laps['IdealLap'].dt.total_seconds()
faster_laps['DiffLapSec'] = faster_laps['DiffLap'].dt.total_seconds()

In [16]:
faster_laps['LapTime'] = faster_laps['LapTime'].astype(str).apply(fix_time)
faster_laps['IdealLap'] = faster_laps['IdealLap'].astype(str).apply(fix_time)
faster_laps['DiffLap'] = faster_laps['DiffLap'].astype(str).apply(fix_time)

df_final = faster_laps

In [17]:
df_final = df_final.sort_values(by=['DiffLapSec'])
df_final

,Driver,LapTime,IdealLap,DiffLap,LapTimeSec,IdealLapSec,DiffLapSec
11,NOR,00:01:09.511000,00:01:09.473000,00:00:00.038000,69.511,69.473,0.038
2,ANT,00:01:09.685000,00:01:09.473000,00:00:00.212000,69.685,69.473,0.212
3,BEA,00:01:09.755000,00:01:09.473000,00:00:00.282000,69.755,69.473,0.282
10,LEC,00:01:09.801000,00:01:09.473000,00:00:00.328000,69.801,69.473,0.328
13,PIA,00:01:09.835000,00:01:09.473000,00:00:00.362000,69.835,69.473,0.362
5,GAS,00:01:09.857000,00:01:09.473000,00:00:00.384000,69.857,69.473,0.384
14,RUS,00:01:09.880000,00:01:09.473000,00:00:00.407000,69.880,69.473,0.407
6,HAD,00:01:09.931000,00:01:09.473000,00:00:00.458000,69.931,69.473,0.458
9,LAW,00:01:09.950000,00:01:09.473000,00:00:00.477000,69.950,69.473,0.477
8,HUL,00:01:09.985000,00:01:09.473000,00:00:00.512000,69.985,69.473,0.512
1,ALO,00:01:10.001000,00:01:09.473000,00:00:00.528000,70.001,69.473,0.528
7,HAM,00:01:10.016000,00:01:09.473000,00:00:00.543000,70.016,69.473,0.543
16,STR,00:01:10.041000,00:01:09.473000,00:00:00.568000,70.041,69.473,0.568
0,ALB,00:01:10.053000,00:01:09.473000,00:00:00.580000,70.053,69.473,0.580
15,SAI,00:01:10.184000,00:01:09.473000,00:00:00.711000,70.184,69.473,0.711
18,VER,00:01:10.403000,00:01:09.473000,00:00:00.930000,70.403,69.473,0.930
12,OCO,00:01:10.438000,00:01:09.473000,00:00:00.965000,70.438,69.473,0.965
4,COL,00:01:10.632000,00:01:09.473000,00:00:01.159000,70.632,69.473,1.159
17,TSU,00:01:10.711000,00:01:09.473000,00:00:01.238000,70.711,69.473,1.238

In [18]:
df_final.to_csv('../data/processed/teste_interlagos.csv', index=False)

In [19]:
df_final

,Driver,LapTime,IdealLap,DiffLap,LapTimeSec,IdealLapSec,DiffLapSec
11,NOR,00:01:09.511000,00:01:09.473000,00:00:00.038000,69.511,69.473,0.038
2,ANT,00:01:09.685000,00:01:09.473000,00:00:00.212000,69.685,69.473,0.212
3,BEA,00:01:09.755000,00:01:09.473000,00:00:00.282000,69.755,69.473,0.282
10,LEC,00:01:09.801000,00:01:09.473000,00:00:00.328000,69.801,69.473,0.328
13,PIA,00:01:09.835000,00:01:09.473000,00:00:00.362000,69.835,69.473,0.362
5,GAS,00:01:09.857000,00:01:09.473000,00:00:00.384000,69.857,69.473,0.384
14,RUS,00:01:09.880000,00:01:09.473000,00:00:00.407000,69.880,69.473,0.407
6,HAD,00:01:09.931000,00:01:09.473000,00:00:00.458000,69.931,69.473,0.458
9,LAW,00:01:09.950000,00:01:09.473000,00:00:00.477000,69.950,69.473,0.477
8,HUL,00:01:09.985000,00:01:09.473000,00:00:00.512000,69.985,69.473,0.512
1,ALO,00:01:10.001000,00:01:09.473000,00:00:00.528000,70.001,69.473,0.528
7,HAM,00:01:10.016000,00:01:09.473000,00:00:00.543000,70.016,69.473,0.543
16,STR,00:01:10.041000,00:01:09.473000,00:00:00.568000,70.041,69.473,0.568
0,ALB,00:01:10.053000,00:01:09.473000,00:00:00.580000,70.053,69.473,0.580
15,SAI,00:01:10.184000,00:01:09.473000,00:00:00.711000,70.184,69.473,0.711
18,VER,00:01:10.403000,00:01:09.473000,00:00:00.930000,70.403,69.473,0.930
12,OCO,00:01:10.438000,00:01:09.473000,00:00:00.965000,70.438,69.473,0.965
4,COL,00:01:10.632000,00:01:09.473000,00:00:01.159000,70.632,69.473,1.159
17,TSU,00:01:10.711000,00:01:09.473000,00:00:01.238000,70.711,69.473,1.238